CREATE TABLE IF NOT EXISTS `appkey` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `app_name` VARCHAR(255) NOT NULL COMMENT '',
  `app_key` VARCHAR(255) NOT NULL COMMENT '',
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `app_name_UNIQUE` (`app_name` ASC)  COMMENT '',
  UNIQUE INDEX `app_key_UNIQUE` (`app_key` ASC)  COMMENT '')
ENGINE = InnoDB;