CREATE TABLE IF NOT EXISTS `user_meta` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id` BIGINT(20) NULL COMMENT '',
  `key` VARCHAR(255) NOT NULL COMMENT '',
  `value` TEXT NOT NULL COMMENT '',
  `created` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `updated` DATETIME NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `FK_user_meta_user_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `FK_user_meta_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;